//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTutor
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Lecturer
    {
        [Key]
        public int staffId { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public int userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
