//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTutor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public int prefId { get; set; }
        public int studentId { get; set; }
        public bool prefered { get; set; }
        public int classId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Class Class { get; set; }
    }
}
