//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTutor
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Preference
    {
        [Key]
        public int prefId { get; set; }
        public int studentId { get; set; }
        public int moduleId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Module Module { get; set; }
    }
}
