//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTutor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Allocations = new HashSet<Allocation>();
            this.Preferences = new HashSet<Preference>();
        }
    
        public int studentId { get; set; }
        public Nullable<int> userId { get; set; }
        public int matricNumber { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string degree { get; set; }
        public int year { get; set; }
        public string NI { get; set; }
        public double paymentRate { get; set; }
        public int maxHour { get; set; }
        public bool applied { get; set; }
        public double workingHour1 { get; set; }
        public double workingHour2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allocation> Allocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preference> Preferences { get; set; }
        public virtual User User { get; set; }
    }
}
